-- Drop anythings
DROP ALL OBJECTS;

CREATE SCHEMA ZC;

CREATE TABLE ZC.ISO_TEST  (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  VERSION BIGINT ,
  CODE VARCHAR(8),
  CONTENT CLOB
);

CREATE TABLE ZC.ISO_MESSAGE  (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  VERSION BIGINT,
  IS_INCOME INTEGER NOT NULL,
  IS_DELIVERED INTEGER NOT NULL,
  CONTENT CLOB
);

CREATE TABLE ZC.ISO_TRANSACTION  (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  VERSION BIGINT,
  ISO_MTI VARCHAR(4),
  ISO_TRACE VARCHAR(6),
  ISO_TX_DATE VARCHAR(12),
  ISO_ACQ_CODE VARCHAR(12),
  ISO_ACC_ID VARCHAR(12),
  IN_MSG_ID BIGINT,
  OUT_MSG_ID BIGINT,
  ACTION_CODE VARCHAR(8),
  COMMENT VARCHAR(512),
  START_DATE VARCHAR(16) NOT NULL,
  END_DATE VARCHAR(16),
  EXPIRE_DATE VARCHAR(16),
  STATUS VARCHAR(3)
);

CREATE SEQUENCE ZC.ISO_TRANSACTION_SEQ;
CREATE SEQUENCE ZC.ISO_MESSAGE_SEQ;
CREATE SEQUENCE ZC.ISO_TEST_SEQ;
